
build:
  stage: build
  variables:
    DEBIAN_FRONTEND: "noninteractive"
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - apt-get update && apt-get -fuy install git build-essential git-buildpackage dpkg-dev fakeroot libssl-dev autoconf pkg-config
    - dpkg-buildpackage -rfakeroot -us -uc -b
    - mkdir debian-packages
    - mv ../*.deb debian-packages/
  artifacts:
    paths:
      - debian-packages/*.deb
    expire_in: 4 weeks

