
build:
  stage: build
  variables:
    DEBIAN_FRONTEND: "noninteractive"
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - apt-get update && apt-get -fuy install git build-essential git-buildpackage
    - gbp buildpackage
